apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customerorderservice
spec:
  replicas: 1
  template:
    metadata:
     name: customerorderservice
     labels:
       run: customerorderservice
       test: customerorderservice
    spec:
      containers:
        - name: customerorderservice
          image: customerorderservice
          ports:
          - containerPort: 9443
          - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: customerorderservice
  labels:
    run: customerorderservice
spec:
  type: NodePort
  selector:
    run: customerorderservice
  ports:
   - protocol: TCP
     port: 9080
     name: http
   - protocol: TCP
     port: 9443
     name: https